options:
  blacklist_ports:
    type: string
    default: "8094"
    description: >
      Comma-separated list of TCP port numbers to skip over when generating
      internal servers used between haproxy and nginx.  Used when a large
      number of sites may interfere with existing unit services, subordinate
      charms, etc.
  cache_inactive_time:
    type: string
    default: ""
    description: >
      Maximum age/time inactive objects are stored in cache. If unspecified,
      use the upstream defaults (currently 10m).
  cache_max_size:
    type: string
    default: ""
    description: >
      Maximum size of content cache storage. If unspecified, the maximum cache
      storage size will be set to 75% of the total disk space, using a 1GB
      minimum size.
  cache_path:
    type: string
    default: "/var/lib/nginx/proxy"
    description: >
      Path or directory to store cached objects.
  enable_cache_background_update:
    default: true
    type: boolean
    description: >
      Default is to enable serving contents from the cache with a
      background subrequest to update objects in cache. This works for
      large objects, but can cause issues with sites updated recently
      to redirect and still have objects in the cache.
  enable_cache_lock:
    default: true
    type: boolean
    description: >
      Default is to restrict to only one request at a time to populate
      new cache elements from the backends. See Nginx'
      proxy_cache_lock.
  enable_prometheus_metrics:
    default: true
    type: boolean
    description: >
      Export metrics for the number of requests and the number of cache hits.
      Prometheus metrics are exposed at /metrics on localhost:9145.
  haproxy_hard_stop_after:
    default: "5m"
    type: string
    description: >
      Tune HAProxy's hard-stop-after to prevent lingering HAProxy processes
      (LP:1874386).
  haproxy_load_balancing_algorithm:
    default: "leastconn"
    type: string
    description: >
      Change the load balancing algorithm used by HAProxy for the
      backends.
  haproxy_processes:
    default: 0
    type: int
    description: >
      Sets the number of HAProxy processes. If both processs and
      threads specified and using HAProxy 2.x and above, the number of
      HAProxy threads will be configured using processes multiplied
      by threads (max. 64).
  haproxy_threads:
    default: 0
    type: int
    description: >
      Sets the number of HAProxy threads. If both processs and
      threads specified and using HAProxy 2.x and above, the number of
      HAProxy threads will be configured using processes multiplied
      by threads (max. 64).
  log_retention:
    type: int
    default: 30
    description: >
      Number of log files to retain during rotation.
  max_connections:
    type: int
    default: 0
    description: >
      Configure maximum number of connections per site on frontend
      HAProxy. Defaults to auto-calculate (0).
  metrics_listen_address:
    type: string
    default: "localhost"
    description: >
      Restrict exposed metrics to listen on certain addresses.
  nagios_context:
    type: string
    default: "juju"
    description: >
      This string is prefixed to the hostname when writing
      exported nagios config fragments.
  nagios_servicegroups:
    default: ""
    type: string
    description: >
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  reuseport:
    default: false
    type: boolean
    description: >
      Use the SO_REUSEPORT socket option, allowing a better load balance on the nginx workers.
      Can result in performance drop due to increased latency on heavy workload.
      See https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/.
  sites:
    default: ""
    type: string
    description: >
      YAML-formatted virtual hosts/sites. See the README.md for more details
      and examples.
  sites_secrets:
    default: ""
    type: string
    description: >
      YAML-formatted dictionary of secrets/keys. e.g.
      site1.local:
        locations:
          "/":
            origin-headers:
              X-Origin-Key: my-origin-secret-key
            signed-url-hmac-key: my-signed-url-secret-key
  tls_cipher_suites:
    default: ""
    type: string
    description: >
      Override default ciphers used for TLS/SSL termination (OpenSSL format).
  tune_tcp_mem_multiplier:
    type: float
    default: 1.5
    description: >
      Tune net.ipv4.tcp_mem, apply multiplier.
  worker_connections:
    default: 768
    type: int
    description: >
      Sets the maximum number of simultaneous connections that can be
      opened by an Nginx worker process.
  worker_processes:
    default: 0
    type: int
    description: >
      Sets the number of Nginx worker processes. Setting to '0' (auto)
      will set based on available CPU cores.
