options:
  cache_max_size:
    type: string
    default: ""
    description: |
      Maximum size of content cache storage. If unspecified, the maximum cache
      storage size will be set to 75% of the total disk space, using a 1GB
      minimum size.
  cache_path:
    type: string
    default: "/var/lib/nginx/proxy"
    description: |
      Path or directory to store cached objects.
  nagios_context:
    type: string
    default: "juju"
    description: |
      This string is prefixed to the hostname when writing
      exported nagios config fragments.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  sites:
    default: ""
    type: string
    description: |
      YAML-formatted virtual hosts/sites. See the README.md for more details
      and examples.
  sites_secrets:
    default: ""
    type: string
    description: |
      YAML-formatted dictionary of secrets/keys. e.g.
      site1.local:
        locations:
          "/":
            origin-headers:
              X-Origin-Key: my-origin-secret-key
            signed-url-hmac-key: my-signed-url-secret-key
  enable_prometheus_metrics:
    default: true
    type: boolean
    description: |
      Export metrics for the number of requests and the number of cache hits.
      Prometheus metrics are exposed at /metrics on port 9145.
