options:
  nagios_context:
    type: string
    default: "juju"
    description: |
      This string is prefixed to the hostname when writing
      exported nagios config fragments.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  sites:
    default: ""
    type: string
    description: |
      YAML-formatted virtual hosts/sites. e.g.
      site1.local:
        backends:
        - 91.189.88.149:80
        - 91.189.88.152:80
  signed-url-hmac-key:
    default: ""
    type: string
    description: |
      Enable signed URL / URL token validation using this key. Use the command
      below to generate a key:

        $ while (b=$(openssl rand -base64 32) ; echo $b; echo $b | base64 -d | hd | grep " 00 " > /dev/null); do :; done | tail -1
