options:
  nagios_context:
    type: string
    default: "juju"
    description: |
      This string is prefixed to the hostname when writing
      exported nagios config fragments.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  sites:
    default: ""
    type: string
    description: |
      YAML-formatted virtual hosts/sites. e.g.
      site1.local:
        backends:
          - 91.189.88.149:80
          - 91.189.88.152:80
        origin-headers:
          - X-Origin-Key: ${secret}
        local-content:
          my-local-content:
            root-path: /var/www/html
  sites_secrets:
    default: ""
    type: string
    description: |
      YAML-formatted dictionary of secrets/keys. e.g.
      site1.local:
        origin-headers:
          X-Origin-Key: my-origin-secret-key
        signed-url-hmac-key: my-signed-url-secret-key
  enable_monitoring:
    default: False
    type: boolean
    description: Enable monitoring
  monitoring_port:
    default: 10000
    type: int
    description: Default monitoring port
  monitoring_allowed_cidr:
    default: "127.0.0.1/32"
    type: string
    description: |
        CIDR allowed ( multiple CIDRs separated by space ) access to the
        monitoring interface.
  monitoring_username:
    default: "haproxy"
    type: string
    description: Monitoring username
  monitoring_password:
    default: "changeme"
    type: string
    description: |
        Password to the monitoring interface ( if "changeme", a new password
        will be generated and displayed in juju-log )
