{
 "title": "Content Cache",
 "description": "Metrics for the content cache filter by sites and/or juju units.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {}
   },
   {
    "name": "juju_unit",
    "label": "juju-unit",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Status Codes",
   "type": "stat",
   "description": "The HTTP status code of the responses from content cache to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 200 | status_code < 300 [2m])) or vector(0)",
     "legendFormat": "200s"
    },
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 300 | status_code < 400 [2m])) or vector(0)",
     "legendFormat": "300s"
    },
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 400 | status_code < 500 [2m])) or vector(0)",
     "legendFormat": "400s"
    },
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 500 | status_code < 600 [2m])) or vector(0)",
     "legendFormat": "500s",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "The response time from client to content cache by hostnames.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json  | unwrap request_time [2m]))",
     "legendFormat": "mean"
    },
    {
     "expr": "max(avg_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json  | unwrap request_time [2m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Requests status",
   "type": "timeseries",
   "description": "The number of total requests and failed requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json [2m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 400 [2m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Failed Requests %",
   "type": "timeseries",
   "description": "The percent of failed requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 400 [2m]))  / sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json [2m]))",
     "legendFormat": "Failure rate %"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "description": "The bytes sent from content cache to clients over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | unwrap bytes(bytes_sent) [2m]))",
     "legendFormat": "Total bandwidth"
    },
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` | unwrap bytes(body_bytes_sent) [1m]))",
     "legendFormat": "Saved bandwidth"
    }
   ]
  },
  {
   "title": "Bandwidth Saved %",
   "type": "timeseries",
   "description": "The ratio of bandwidth save to bandwidth.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status=\"HIT\" | unwrap body_bytes_sent [2m])) / sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | unwrap bytes_sent [2m]))",
     "legendFormat": "Saving rate"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "The number of cache hits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json [2m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` [1m]))",
     "legendFormat": "Cache hits"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "timeseries",
   "description": "The number of cache hit over total requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` [2m])) / sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} [2m]))",
     "legendFormat": "Cache hit rate"
    }
   ]
  }
 ]
}