{
 "title": "content cache",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {}
   },
   {
    "name": "juju_unit",
    "label": "juju-unit",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of requests from clients to content cache over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json [2m])) or vector(0)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "description": "The number of requests with status code greater than or equal to 400.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 400 [2m])) or vector(0)",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Repsonse Time",
   "type": "timeseries",
   "description": "The response time from client to content cache by hostnames.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(avg_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json  | unwrap request_time [2m])) or vector(0)",
     "legendFormat": "Response time (ms)"
    }
   ]
  },
  {
   "title": "Failed Requests %",
   "type": "timeseries",
   "description": "The percentage of failed requests over total requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | status_code >= 400 [2m])) / sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` [2m])) or vector(0)",
     "legendFormat": "Failure rate"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "description": "The total bytes sent from content cache to clients over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | unwrap bytes_sent [2m])) or vector(0)",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "timeseries",
   "description": "The number of cache hit over total requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` [2m])) / sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} [2m])) or vector(0)",
     "legendFormat": "Cache hit rate"
    }
   ]
  },
  {
   "title": "Bandwidth Saved",
   "type": "timeseries",
   "description": "The total bytes from content cache to client of response body with cache hits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status=\"HIT\" | unwrap body_bytes_sent [1m])) or vector(0)",
     "legendFormat": "Bytes saved"
    }
   ]
  },
  {
   "title": "Bandwidth Saved %",
   "type": "timeseries",
   "description": "The ratio of bandwidth save to bandwidth.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status=\"HIT\" | unwrap body_bytes_sent [2m])) / sum(sum_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | unwrap bytes_sent [2m])) or vector(0)",
     "legendFormat": "Saving rate"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "The number of cache hits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `HIT` [1m])) or vector(0)",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "The number of cache miss",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/var/log/nginx/${juju_unit}/${site}\\\\.cache\\\\.log\"} | json | cache_status = `MISS` [1m])) or vector(0)",
     "legendFormat": "Misses"
    }
   ]
  }
 ]
}