# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Integration test for client IP hashing in content-cache logs."""

import hashlib
import json

import pytest
from juju.application import Application
from juju.model import Model
from juju.unit import Unit

from src import nginx_manager
from src.charm import unit_name_to_instance_name
from tests.integration.helpers import (
    BACKENDS_CONFIG_NAME,
    PROXY_CACHE_VALID_CONFIG_NAME,
    CacheTester,
    read_file,
)

CLIENT_IP_HASH_SALT_CONFIG_NAME = "client-ip-hash-salt"


def _last_non_empty_line(content: str) -> str:
    """Return the last non-empty line of some log content.

    The access and cache logs are shared across the whole integration test session and are
    never truncated, so earlier tests' entries may already be present. Only the last line is
    guaranteed to have been generated by the most recent request.

    Args:
        content: The full log file content.

    Returns:
        The last non-empty line.
    """
    lines = [line for line in content.splitlines() if line.strip()]
    assert lines, "Log file has no entries"
    return lines[-1]


@pytest.mark.abort_on_fail
@pytest.mark.asyncio
async def test_client_ip_hash_salt(
    app: Application,
    config_app: Application,
    cache_tester: CacheTester,
    http_ok_ip: str,
    model: Model,
) -> None:
    """
    arrange: A working application of content-cache charm integrated with config charm.
    act:
        1. Make a request to the content-cache with client IP hashing disabled, to learn the
           client address as nginx sees it (which may differ from the unit's own address).
        2. Configure client-ip-hash-salt with a secret, and make another request.
    assert:
        1. The new access and cache log entries contain the salted SHA-256 digest of the
           client address seen in step 1, and not the plaintext client address.
    """
    unit: Unit = app.units[0]
    instance_name = unit_name_to_instance_name(unit.name)

    config = dict(CacheTester.BASE_CONFIG)
    config[BACKENDS_CONFIG_NAME] = f"http://{http_ok_ip}:80"
    config[PROXY_CACHE_VALID_CONFIG_NAME] = '["200 10s"]'
    await cache_tester.setup_config(config)
    await cache_tester.integrate_config()
    await model.wait_for_idle([app.name, config_app.name], status="active", timeout=10 * 60)

    # 1. Baseline request with hashing disabled to learn the real client address.
    response = await cache_tester.query_cache(path="/")
    assert response.status_code == 200
    baseline_cache_log = await read_file(
        unit, nginx_manager._get_cache_log_path("30000", instance_name)
    )
    baseline_entry: dict = json.loads(_last_non_empty_line(baseline_cache_log))
    client_ip = baseline_entry["client_address"]

    # 2. Enable client IP hashing and make another request.
    salt = "some-test-salt"
    secret_uri = await model.add_secret("client-ip-hash-salt", [f"salt={salt}"])
    await model.grant_secret("client-ip-hash-salt", app.name)
    await app.set_config({CLIENT_IP_HASH_SALT_CONFIG_NAME: secret_uri})
    await model.wait_for_idle([app.name, config_app.name], status="active", timeout=10 * 60)

    response = await cache_tester.query_cache(path="/")
    assert response.status_code == 200

    expected_digest = hashlib.sha256((salt + client_ip).encode("utf-8")).hexdigest()

    access_log = await read_file(unit, nginx_manager._get_access_log_path("30000", instance_name))
    last_access_line = _last_non_empty_line(access_log)
    assert expected_digest in last_access_line
    assert client_ip not in last_access_line

    cache_log = await read_file(unit, nginx_manager._get_cache_log_path("30000", instance_name))
    cache_entry: dict = json.loads(_last_non_empty_line(cache_log))
    assert cache_entry["client_address"] == expected_digest

    # Clean up so subsequent tests are not affected by client IP hashing being enabled.
    await app.reset_config([CLIENT_IP_HASH_SALT_CONFIG_NAME])
    await model.wait_for_idle([app.name, config_app.name], status="active", timeout=10 * 60)
