name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.6/stable
      provider: lxd
      modules: '["test_charm", "test_tls_cert", "test_metric"]'
      working-directory: ./content-cache
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
