name: Promote charm for content-cache

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - 1/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - 1/stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
      working-directory: ./content-cache-backends-config
    secrets: inherit
